### ISSUE TITLE
关于界面设计

### ISSUE THREAD

**Issue by jonahfang** [BelinChung/weapp-hiapp#1]
这个程序的界面超赞！我原来用过bootstrap,现在用了微信小程序，感觉缺少更高层次的界面css框架，如果你能提供类似功能，我可以付费购买。我的qq号是：499233138.

**Comment by BelinChung** [comment]
敬请期待微信小程序开放后，其他大神为小程序出的UI框架吧。

**Comment by jonahfang** [comment]
把你平时常用的一些界面样式整理成wxss/wxml, 我也可以接受。（因为无法用qq发送邮件到你的email,所以只能在这里了，不好意思）。

**Comment by BelinChung** [comment]
@jonahfang https://github.com/weui/weui-wxss 这个是官方出品的UI库，非常全面了。

**Comment by xhanglizhu** [comment]
@BelinChung 您好，请问webapp 这个是用什么框架开发的？
